techLead: Benjamin
techLeadRate: 50
candidates:
  - David
  - Heng
  - Tino
  - Steven
  - Richard
  - Jacky
  - Stoney
  - Tom
  - Ada
  - Arden
  - Bill
  - Bo-Yin
  - Joe
  - Bruce
  - Cheryl
  - Jacob
  - Hung-Wei
  - Johnny
voteValueRangeLower: 1
voteValueRangeUpper: 5
