/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Vote extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1589681621973709049L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Vote\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"candidate\",\"type\":\"string\"},{\"name\":\"vote\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Vote> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Vote> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Vote> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Vote> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Vote> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Vote to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Vote from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Vote instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Vote fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence candidate;
  private int vote;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Vote() {}

  /**
   * All-args constructor.
   * @param candidate The new value for candidate
   * @param vote The new value for vote
   */
  public Vote(java.lang.CharSequence candidate, java.lang.Integer vote) {
    this.candidate = candidate;
    this.vote = vote;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return candidate;
    case 1: return vote;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: candidate = (java.lang.CharSequence)value$; break;
    case 1: vote = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'candidate' field.
   * @return The value of the 'candidate' field.
   */
  public java.lang.CharSequence getCandidate() {
    return candidate;
  }


  /**
   * Sets the value of the 'candidate' field.
   * @param value the value to set.
   */
  public void setCandidate(java.lang.CharSequence value) {
    this.candidate = value;
  }

  /**
   * Gets the value of the 'vote' field.
   * @return The value of the 'vote' field.
   */
  public int getVote() {
    return vote;
  }


  /**
   * Sets the value of the 'vote' field.
   * @param value the value to set.
   */
  public void setVote(int value) {
    this.vote = value;
  }

  /**
   * Creates a new Vote RecordBuilder.
   * @return A new Vote RecordBuilder
   */
  public static com.example.Vote.Builder newBuilder() {
    return new com.example.Vote.Builder();
  }

  /**
   * Creates a new Vote RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Vote RecordBuilder
   */
  public static com.example.Vote.Builder newBuilder(com.example.Vote.Builder other) {
    if (other == null) {
      return new com.example.Vote.Builder();
    } else {
      return new com.example.Vote.Builder(other);
    }
  }

  /**
   * Creates a new Vote RecordBuilder by copying an existing Vote instance.
   * @param other The existing instance to copy.
   * @return A new Vote RecordBuilder
   */
  public static com.example.Vote.Builder newBuilder(com.example.Vote other) {
    if (other == null) {
      return new com.example.Vote.Builder();
    } else {
      return new com.example.Vote.Builder(other);
    }
  }

  /**
   * RecordBuilder for Vote instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Vote>
    implements org.apache.avro.data.RecordBuilder<Vote> {

    private java.lang.CharSequence candidate;
    private int vote;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Vote.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.candidate)) {
        this.candidate = data().deepCopy(fields()[0].schema(), other.candidate);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.vote)) {
        this.vote = data().deepCopy(fields()[1].schema(), other.vote);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Vote instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Vote other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.candidate)) {
        this.candidate = data().deepCopy(fields()[0].schema(), other.candidate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vote)) {
        this.vote = data().deepCopy(fields()[1].schema(), other.vote);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'candidate' field.
      * @return The value.
      */
    public java.lang.CharSequence getCandidate() {
      return candidate;
    }


    /**
      * Sets the value of the 'candidate' field.
      * @param value The value of 'candidate'.
      * @return This builder.
      */
    public com.example.Vote.Builder setCandidate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.candidate = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'candidate' field has been set.
      * @return True if the 'candidate' field has been set, false otherwise.
      */
    public boolean hasCandidate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'candidate' field.
      * @return This builder.
      */
    public com.example.Vote.Builder clearCandidate() {
      candidate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'vote' field.
      * @return The value.
      */
    public int getVote() {
      return vote;
    }


    /**
      * Sets the value of the 'vote' field.
      * @param value The value of 'vote'.
      * @return This builder.
      */
    public com.example.Vote.Builder setVote(int value) {
      validate(fields()[1], value);
      this.vote = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'vote' field has been set.
      * @return True if the 'vote' field has been set, false otherwise.
      */
    public boolean hasVote() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'vote' field.
      * @return This builder.
      */
    public com.example.Vote.Builder clearVote() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Vote build() {
      try {
        Vote record = new Vote();
        record.candidate = fieldSetFlags()[0] ? this.candidate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.vote = fieldSetFlags()[1] ? this.vote : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Vote>
    WRITER$ = (org.apache.avro.io.DatumWriter<Vote>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Vote>
    READER$ = (org.apache.avro.io.DatumReader<Vote>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.candidate);

    out.writeInt(this.vote);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.candidate = in.readString(this.candidate instanceof Utf8 ? (Utf8)this.candidate : null);

      this.vote = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.candidate = in.readString(this.candidate instanceof Utf8 ? (Utf8)this.candidate : null);
          break;

        case 1:
          this.vote = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










